services:
  python-dev:
    image: python:3.11-slim
    container_name: python-dev-env
    working_dir: /repo
    volumes:
      - ~/repo:/repo
    environment:
      - TERM=xterm-256color
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
      - HOST_USER=${HOST_USER}
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/container_ready"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    command: /bin/bash -c "
      groupadd -g $HOST_GID $HOST_USER || true;
      useradd -u $HOST_UID -g $HOST_GID -M -s /bin/bash $HOST_USER || true;
      echo '$HOST_USER ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
      chown -R $HOST_UID:$HOST_GID /repo &&
      apt update && 
      apt install -y 
        neovim 
        git &&
      pip install --upgrade pip &&
      pip install -r dev-container/requirements.txt &&
      echo 'CONTAINER SETUP COMPLETE' &&
      touch /tmp/container_ready &&
      su - $HOST_USER -c 'cd /repo && exec /bin/bash'
      "
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge